site_name: Stolcke PCFG Parser
site_description: Probabilistic Earley (Stolcke) parser with prefix probabilities in Python.
site_url: https://cbrew.github.io/stolcke-pcfg/
repo_url: https://github.com/cbrew/stolcke-pcfg
theme:
  name: material
  features:
    - navigation.tracking
    - content.code.copy
nav:
  - Home: index.md
  - Architecture: architecture.md
  - API: api.md
  - CLI: cli.md
  - Grammar: grammar.md
  - Unit Transform: unit_transform.md
  - Adapter: adapter.md
  - Constrained Decoding: constrained_decoding.md
  - Examples: examples.md
  - JSON Constraints: json_constraints.md
  - Development: development.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - search
# trigger rebuild
